// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento_box: dynamic(() => import("./BentoBox")),
  hero: dynamic(() => import("./Hero")),
  keyboard_color_changer: dynamic(() => import("./KeyboardColorChanger")),
};
